DEV 59 hawkinR v1.2.0 w/ new database functions
HawkinDynamics/hawkinR pull request #31
Opened 2024-10-17 14:44 UTC by laureng-hd

- addition of buildDB and syncDB functions for creating and storing local database files
- get_tests functions now accept dates as text strings for `from` and `to` parameters
- bug fix for test type validation to accept/check TS tests

2024-10-21 13:55 UTC, awales-hd commented on .Rhistory
> +?unwrap
@laureng-hd  what does `?unwrap` do here?

2024-10-24 22:00 UTC, laureng-hd commented
That .Rhistory file is showing a prompt log. I was trouble shooting a way to flatten the json array of teams and groups to change them to a comma separated string. ChatGPT suggested `unwrap` function. So, I looked it up in the RStudio help docs by using `?function`. It's an IDE help command. I didn't even end up using it in the code.

Lauren Green, M.S CSCS RSCC*D PES
Performance Consultant
(320) 291-5144 LinkedIn<http://www.linkedin.com/laurengreencscs> ***@***.***>
***@***.***


From: Andrew Wales ***@***.***>
Sent: Monday, October 21, 2024 6:56 AM
To: HawkinDynamics/hawkinR ***@***.***>
Cc: Lauren Green ***@***.***>; Mention ***@***.***>
Subject: Re: [HawkinDynamics/hawkinR] DEV 59 hawkinR v1.2.0 w/ new database functions (PR #31)

External Sender: Please Use Caution

@awales-hd commented on this pull request.

________________________________

In .Rhistory<https://github.com/HawkinDynamics/hawkinR/pull/31#discussion_r1808877683>:

> @@ -158,3 +158,5 @@ github_token <- Sys.getenv("GITHUB_PAT")

 Sys.getenv("GITHUB_PAT")

 logger::log_formatter(logger::formatter_glue_or_sprintf)

 devtools::load_all(".")

+?unwrap

@laureng-hd<https://github.com/laureng-hd> what does ?unwrap do here?

-
Reply to this email directly, view it on GitHub<https://github.com/HawkinDynamics/hawkinR/pull/31#pullrequestreview-2382198762>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BB2O3EWABB2PXTBYIW4LCNLZ4UBYJAVCNFSM6AAAAABQD5SLGCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBSGE4TQNZWGI>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-12-30 20:52 UTC, awales-hd requested changes

2024-12-30 20:52 UTC, awales-hd commented on .Rhistory
@laureng-hd  if you don't want to check in .Rhistory, can you remove from this PR? e.g.

```
git checkout DEV-579-hawkinR-v1.2.0-Workflow-Updates
git rm --cached .rHistory     # (wont delete the file, just removes from git)
git commit -m "removed .rHistory from version control."
git push origin DEV-579-hawkinR-v1.2.0-Workflow-Updates
```

2024-12-30 20:52 UTC, awales-hd commented on DESCRIPTION
> +Title: hawkinR v1.2.0 - Hawkin Dynamics API
just suggestion not to keep track of version in two places
```suggestion
Title: hawkinR - Hawkin Dynamics API
```

2024-12-30 20:52 UTC, awales-hd commented on R/buildDB.R
> +    " in ", span, " day incriments"
```suggestion
    " in ", span, " day increments"
```

2024-12-30 20:52 UTC, awales-hd commented on R/buildDB.R
@laureng-hd  when I ran buildDB, it seemed to fetch data successfully, but I got 14 'warnings', 2 of which I copied below just as examples -- are these expected? Just wanted to make sure they were okay:
```
Warning messages:
1: In replace_headers(df = trialMetrics, typeId = typeId) :
  The following columns have no match in the header lookup: Weight in Newtons(N), active, Net Impulse Ratio, Force At Min Displacement(N), Relative Force at 50 ms (BW)(N/kg), Relative Force at 250 ms (BW)(N/kg), Relative Force at 150 ms (BW)(N/kg), Relative Peak Force (BW)(N/kg), Relative Force at 200 ms (BW)(N/kg), Relative Force at 0 ms (BW)(N/kg), Relative Force at 100 ms (BW)(N/kg)
2: In replace_headers(df = trialMetrics, typeId = typeId) :
  The following columns have no match in the header lookup: Weight in Newtons(N), active, Net Impulse Ratio, Force At Min Displacement(N), Relative Force at 50 ms (BW)(N/kg), Relative Force at 250 ms (BW)(N/kg), Relative Force at 150 ms (BW)(N/kg), Relative Peak Force (BW)(N/kg), Relative Force at 200 ms (BW)(N/kg), Relative Force at 0 ms (BW)(N/kg), Relative Force at 100 ms (BW)(N/kg)
```

2024-12-30 20:52 UTC, awales-hd commented on README.Rmd
> +  includeInactive = FALSE , # Include intactive tests in data
```suggestion
  includeInactive = FALSE , # Include inactive tests in data
```

2024-12-30 20:52 UTC, awales-hd commented on README.Rmd
> +  includeInactive = FALSE, # Include intactive tests in data
```suggestion
  includeInactive = FALSE, # Include inactive tests in data
```

2024-12-30 20:52 UTC, awales-hd commented on README.Rmd
> +  newFile = NULL # Optionally provide new file path to duplicate orignal file
```suggestion
  newFile = NULL # Optionally provide new file path to duplicate original file 
```

2024-12-30 20:52 UTC, awales-hd commented on README.md
> +- `syncDB()` - This function updates an existing test database by
@laureng-hd  when I ran syncDB, pointing to the same db file I had created when I ran buildDB, I got the following message, wanted to make sure it was expected?
```
INFO [2024-12-30 12:50:37] hawkinR/syncDB -> Checking for new tests and updates since 2024-12-30
SUCCESS [2024-12-30 12:50:38] hawkinR/get_tests -> 1 active tests returned. Last tested: 2024-12-30 12:37:00 | Last Synced: 2024-12-30 12:37:11
Error in `dplyr::bind_rows()`:
! Can't combine `..1$active` <character> and `..2$active` <logical>.
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In replace_headers(df = trialMetrics, typeId = typeId) :
  The following columns have no match in the header lookup: Weight in Newtons(N), active
```

2024-12-30 20:55 UTC, awales-hd commented
@laureng-hd  see my individual suggestions/questions above. Main thing was that I got warnings both when I ran buildDB and when I ran syncDB, and I wanted to make sure those were expected.  This is what I used to test:

```
load_all('/Users/awales/hd/hawkinR')

get_access("jIFQzD.K3QUmSFPPSZzhfVsem7YUvl6AS8dq")

## Build Local DB File
buildDB(
  startDate = "2024-01-01", # begining date to recall from. Date string or timestamp
  includeInactive = FALSE , # Include intactive tests in data
  testType = "all", # specificy individual test type or all combined
  fileName = "./my-database.rds", # file name and path
  fileType = "rds", # file type extension
  span = 30 # number of days to iterate over when calling tests
)

warnings()

## Update Local File
syncDB(
  file = "./my-database.rds", # path to current file
  includeInactive = FALSE, # Include intactive tests in data
  newFile = NULL # Optionally provide new file path to duplicate orignal file 
)

2025-01-02 09:07 UTC, laureng-hd commented on README.md
> +- `syncDB()` - This function updates an existing test database by
@awales-hd those warnings were put in for error logs, but no not expected. I think there were some metric names that were overlooked or spelled incorrectly.

2025-01-02 09:10 UTC, laureng-hd commented
@awales-hd I updated the MetricLibrary data file and hopefully that addressed those warnings from typos or incorrect mapping.

2025-01-07 23:48 UTC, laureng-hd commented
@awales-hd ready for another review when you get a chance.

- corrections to linting errors and misspellings
- all `get_tests()` data frame metric headers returned in snake_case.
- update of MetricDictionary to include 'cleaned' metric headers for reference to `get_tests()` outputs

2025-01-08 19:10 UTC, laureng-hd commented
@awales-hd fix to get_access. Ready for review

2025-01-31 01:56 UTC, closed without merging